=== leeroybrun/tasksManagerXML/src/task.dtd
<!ELEMENT taskManager (tasks,events,resources,locations,ui)>
        <!ELEMENT tasks (task)*>
        <!ELEMENT task (status,description,assignedTo,progress?,comments?,place?,priority?,duration?)>
        <!ATTLIST task
                id ID #REQUIRED>
        <!ELEMENT status EMPTY>
        <!ATTLIST status
                value (NOT_STARTED|COMPLETED|IN_PROGRESS) #REQUIRED>
        <!ELEMENT duration EMPTY>
        <!ATTLIST duration
                hour CDATA #REQUIRED>
        <!ELEMENT priority EMPTY>
        <!ATTLIST priority
                value (HIGH|NORMAL|LOW) #REQUIRED>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT assignedTo EMPTY>
        <!ATTLIST assignedTo
                resource IDREF #REQUIRED>
        <!ELEMENT progress EMPTY>
        <!ATTLIST progress
                value CDATA #REQUIRED>
        <!ELEMENT comments (comment)*>
        <!ELEMENT comment (#PCDATA)>
        <!ATTLIST comment
                from IDREF #REQUIRED>
        <!ELEMENT place (#PCDATA)>
        <!ATTLIST place
                loc CDATA #REQUIRED>
        <!ELEMENT events (event)*>
        <!ELEMENT event (((from,to)|(from)|(to)), (operande|operator)+)>
        <!ELEMENT operande (taskValue|now|value)>
        <!ELEMENT from EMPTY>
        <!ATTLIST from
                    task IDREFS #REQUIRED>
        <!ELEMENT to EMPTY>
        <!ATTLIST to
                task IDREFS #REQUIRED>
        <!ELEMENT taskValue EMPTY>
        <!ATTLIST taskValue
                task IDREF #REQUIRED
                element CDATA #REQUIRED>
        <!ELEMENT now EMPTY>
        <!ELEMENT value (#PCDATA)>
        <!ELEMENT operator EMPTY>
        <!ATTLIST operator
                name (AND|OR|EQUAL|NOT_EQUAL|LESS_THAN|BIGGER_THAN) #REQUIRED>
        <!ELEMENT resources (person)*>
        <!ELEMENT person (#PCDATA)>
        <!ATTLIST person
                birthday CDATA #IMPLIED
                firstName CDATA #REQUIRED
                id ID #REQUIRED
                lastName CDATA #REQUIRED>
        <!ELEMENT locations (location)*>
        <!ELEMENT location EMPTY>
        <!ATTLIST location
                id CDATA #REQUIRED
                name CDATA #REQUIRED>
        <!ELEMENT ui (rectangle|circle)*>
        <!ELEMENT rectangle (position,size)>
        <!ATTLIST rectangle
                task IDREF #REQUIRED>
        <!ELEMENT position EMPTY>
        <!ATTLIST position
                x CDATA #REQUIRED
                y CDATA #REQUIRED>
        <!ELEMENT size EMPTY>
        <!ATTLIST size
                height CDATA #REQUIRED
                width CDATA #REQUIRED>
        <!ELEMENT circle (position)>
        <!ATTLIST circle
                task IDREF #REQUIRED
                radius CDATA #REQUIRED>

=== leeroybrun/tasksManagerXML/tasksList.xml
<?xml version="1.0"?>
<!DOCTYPE taskManager SYSTEM "task.dtd">
<?xml-stylesheet type="text/xsl" href="tasksList.xsl"?>
<taskManager>
    <tasks>
        <task id="task_0">
            <status value="IN_PROGRESS"/>
            <description>Create a task manager</description>
            <assignedTo resource="res_1"/>
            <progress value="80"/>
            <comments>
                <comment from="res_1">Started to work on this ! :D</comment>
            </comments>
            <place loc="loc_2"/>
            <duration hour="200"/>
        </task>
        <task id="task_1">
            <status value="COMPLETED"/>
            <description>Create XML Schema</description>
            <assignedTo resource="res_1"/>
            <progress value="80"/>
            <place loc="loc_2"/>
            <priority value="HIGH"/>
        </task>
        <task id="task_2">
            <status value="IN_PROGRESS"/>
            <description>Create DTD</description>
            <assignedTo resource="res_2"/>
            <progress value="0"/>
            <comments>
                <comment from="res_1">Started to work on this ! :D</comment>
            </comments>
            <place loc="loc_2"/>
        </task>
        <task id="task_3">
            <status value="NOT_STARTED"/>
            <description>Create DOC for Mr. Zyssman</description>
            <assignedTo resource="res_2"/>
            <progress value="0"/>
        </task>
    </tasks>
    <events>
        <event>
            <from task="task_1"/>
            <to task="task_2"/>
            <operande>
                <taskValue task="task_1" element="status"/>
            </operande>
            <operande>
                <value>COMPLETED</value>
            </operande>
            <operator name="EQUAL"/>
            <operande>
                <taskValue task="task_1" element="progress"/>
            </operande>
            <operande>
                <value>70</value>
            </operande>
            <operator name="BIGGER_THAN"/>
            <operator name="OR"/>
        </event>
        <event>
            <to task="task_0 task_1 task_2"/>
            <operande>
                <now/>
            </operande>
            <operande>
                <value>2014-10-20</value>
            </operande>
            <operator name="BIGGER_THAN"/>
        </event>
        <event>
            <from task="task_0"/>
            <operande>
                <now/>
            </operande>
            <operande>
                <value>2014-10-20</value>
            </operande>
            <operator name="BIGGER_THAN"/>
        </event>
    </events>
    <resources>
        <person firstName="Florian" lastName="Zysset" birthday="1990-12-02" id="res_1">
            Florian Zysset travaille Ã  Infoteam etc...etc...
        </person>
        <person firstName="Leeroy" lastName="Brun" birthday="1992-02-19" id="res_2"/>
    </resources>
    <locations>
        <location name="Cuisine" id="loc_1"/>
        <location name="HEIG-VD" id="loc_2"/>
        <location name="Home" id="loc_3"/>
    </locations>
    <ui>
        <rectangle task="task_1">
            <position x="1" y="2"/>
            <size height="200" width="200"/>
        </rectangle>
        <circle task="task_2" radius="200">
            <position x="1" y="2"/>
        </circle>
    </ui>
</taskManager>

=== leeroybrun/tasksManagerXML/UI/tasks.xml
<?xml version="1.0"?>
<!DOCTYPE taskManager SYSTEM "task.dtd">
<?xml-stylesheet type="text/xsl" href="tasksSVG.xsl"?>
<taskManager>
    <tasks>
        <task id="task_0">
            <status value="IN_PROGRESS"/>
            <description>Create a task manager</description>
            <assignedTo resource="res_1"/>
            <progress value="80"/>
            <comments>
                <comment from="res_1">Started to work on this ! :D</comment>
            </comments>
            <place loc="loc_2"/>
            <duration hour="200"/>
        </task>
        <task id="task_1">
            <status value="COMPLETED"/>
            <description>Create XML Schema</description>
            <assignedTo resource="res_1"/>
            <progress value="80"/>
            <place loc="loc_2"/>
            <priority value="HIGH"/>
        </task>
        <task id="task_2">
            <status value="IN_PROGRESS"/>
            <description>Create DTD</description>
            <assignedTo resource="res_2"/>
            <progress value="0"/>
            <comments>
                <comment from="res_1">Started to work on this ! :D</comment>
            </comments>
            <place loc="loc_2"/>
        </task>
        <task id="task_3">
            <status value="NOT_STARTED"/>
            <description>Create DOC for Mr. Zyssman</description>
            <assignedTo resource="res_2"/>
            <progress value="0"/>
        </task>
    </tasks>
    <events>
        <event>
            <from task="task_0"/>
            <to task="task_2"/>
            <operande>
                <value>COMPLETED</value>
            </operande>
            <operande>
                <taskValue task="task_1" element="status"/>
            </operande>
            <operator name="EQUAL"/>
            <operande>
                <value>70</value>
            </operande>
            <operande>
                <taskValue task="task_1" element="progress"/>
            </operande>
            <operator name="BIGGER_THAN"/>
            <operator name="OR"/>
        </event>
        <event>
            <from task="task_1"/>
            <to task="task_2 task_3"/>
            <operande>
                <value>2014-10-20</value>
            </operande>
            <operande>
                <now/>
            </operande>
            <operator name="BIGGER_THAN"/>
        </event>
        <event>
            <from task="task_0"/>
            <to task="task_3"/>
            <operande>
                <value>2014-10-20</value>
            </operande>
            <operande>
                <now/>
            </operande>
            <operator name="BIGGER_THAN"/>
        </event>
    </events>
    <resources>
        <person firstName="Florian" lastName="Zysset" birthday="1990-12-02" id="res_1">
            Florian Zysset travaille Ã  Infoteam etc...etc...
        </person>
        <person firstName="Leeroy" lastName="Brun" birthday="1992-02-19" id="res_2"/>
    </resources>
    <locations>
        <location name="Cuisine" id="loc_1"/>
        <location name="HEIG-VD" id="loc_2"/>
        <location name="Home" id="loc_3"/>
    </locations>
    <ui>
        <rectangle task="task_0">
            <position x="500" y="20"/>
            <size height="100" width="270"/>
        </rectangle>
        <circle task="task_1" radius="70">
            <position x="700" y="500"/>
        </circle>
        <rectangle task="task_2">
            <position x="300" y="700"/>
            <size height="100" width="200"/>
        </rectangle>
        <rectangle task="task_3">
            <position x="1100" y="150"/>
            <size height="80" width="350"/>
        </rectangle>
    </ui>
</taskManager>
